# Use official Tomcat image
FROM tomcat:10.1-jdk17-temurin

# Remove default ROOT webapp (optional)
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your WAR file into Tomcat webapps directory
COPY EmployeeManagementSystem.war /usr/local/tomcat/webapps/EmployeeManagementSystem.war

# Expose port 8080 for Render
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
